### ISSUE TITLE
role installing with ansible-galaxy failed

### ISSUE THREAD

**Issue by murata-yu** [NVIDIA/deepops#1140]
Hi, 
When I ran the `scripts/setup.sh`, I got an error and couldn't install the role with ansible-galaxy.

I think this is because the version of `MarkupSafe` has been updated and `soft_unicode` has been removed.

So I installed `MarkupSafe == 2.0.1`.

I can create this PR if you wish.

---

# Environment
- deepops ver: 21.06
- python ver: 3.8.10
- OS: ubuntu 20.04

# Error message
```
./scripts/setup.sh

Get:1 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Hit:2 http://us.archive.ubuntu.com/ubuntu focal InRelease
Get:3 http://us.archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://us.archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 336 kB in 2s (206 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
sshpass is already the newest version (1.06-1).
git is already the newest version (1:2.25.1-1ubuntu3.2).
wget is already the newest version (1.20.3-1ubuntu2).
python3-virtualenv is already the newest version (20.0.17-1ubuntu0.4).
virtualenv is already the newest version (20.0.17-1ubuntu0.4).
0 upgraded, 0 newly installed, 0 to remove and 101 not upgraded.
Current version of Ansible is 2.9.21
Configuration directory './config' exists, not overwriting
Updating Ansible Galaxy roles...
Traceback (most recent call last):
  File "/opt/deepops/env/bin/ansible-galaxy", line 62, in <module>
    import ansible.constants as C
  File "/opt/deepops/env/lib/python3.8/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/deepops/env/lib/python3.8/site-packages/markupsafe/__init__.py)
Traceback (most recent call last):
  File "/opt/deepops/env/bin/ansible-galaxy", line 62, in <module>
    import ansible.constants as C
  File "/opt/deepops/env/lib/python3.8/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/deepops/env/lib/python3.8/site-packages/markupsafe/__init__.py)
Traceback (most recent call last):
  File "/opt/deepops/env/bin/ansible-galaxy", line 62, in <module>
    import ansible.constants as C
  File "/opt/deepops/env/lib/python3.8/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/deepops/env/lib/python3.8/site-packages/markupsafe/__init__.py)
Traceback (most recent call last):
  File "/opt/deepops/env/bin/ansible-galaxy", line 62, in <module>
    import ansible.constants as C
  File "/opt/deepops/env/lib/python3.8/site-packages/ansible/constants.py", line 12, in <module>
    from jinja2 import Template
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/opt/deepops/env/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/opt/deepops/env/lib/python3.8/site-packages/markupsafe/__init__.py)

*** Setup complete ***
To use Ansible, run: source /opt/deepops/env/bin/activate
```

# Solution
```
pip install MarkupSafe==2.0.1
./scripts/setup.sh
```

**Comment by ajdecon** [comment]
The fix for this is already in the master branch, and will be included in the next release: https://github.com/NVIDIA/deepops/blob/master/scripts/setup.sh#L120
