### ISSUE TITLE
Failed at “TASK [kubernetes/client : Copy kubectl binary to ansible host]”

### ISSUE THREAD

**Issue by saladin101** [NVIDIA/deepops#258]
I was setup the k8s by following the **docs/dgx-pod.md**, when I run the command 

> ansible-playbook -l vm01.deepops.rt,localhost -i config/inventory -b playbooks/k8s-cluster.yml -vvv

and i get the messages 
```
TASK [kubernetes/client : Copy kubectl binary to ansible host] *********************************************************************************************************************
task path: /root/deepops/kubespray/roles/kubernetes/client/tasks/main.yml:55
Using module file /usr/lib/python2.7/site-packages/ansible/modules/net_tools/basics/slurp.py
<192.168.205.101> ESTABLISH SSH CONNECTION FOR USER: root
<192.168.205.101> SSH: EXEC ssh -o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=60 -o 'ControlPath=~/.ssh/ansible-%r@%h:%p' 192.168.205.101 '/bin/sh -c '"'"'/usr/bin/python && sleep 0'"'"''
The full traceback is:
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 140, in run
    res = self._execute()
  File "/usr/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 612, in _execute
    result = self._handler.run(task_vars=variables)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/fetch.py", line 95, in run
    slurpres = self._execute_module(module_name='slurp', module_args=dict(src=source), task_vars=task_vars)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 843, in _execute_module
    res = self._low_level_execute_command(cmd, sudoable=sudoable, in_data=in_data)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 962, in _low_level_execute_command
    rc, stdout, stderr = self._connection.exec_command(cmd, in_data=in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 1145, in exec_command
    (returncode, stdout, stderr) = self._run(cmd, in_data, sudoable=sudoable)
  File "/usr/lib/python2.7/site-packages/ansible/plugins/connection/ssh.py", line 396, in wrapped
    display.vvv(return_tuple, host=self.host)
  File "/usr/lib/python2.7/site-packages/ansible/utils/display.py", line 183, in vvv
    return self.verbose(msg, host=host, caplevel=2)
  File "/usr/lib/python2.7/site-packages/ansible/utils/display.py", line 206, in verbose
    self.display("<%s> %s" % (host, msg), color=C.COLOR_VERBOSE, screen_only=True)
MemoryError

fatal: [vm01.deepops.rt]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

what should i do ?

**Comment by dholt** [comment]
Do you have any idea what would be causing a "MemoryError"?

You can find kubectl on the kubernetes worker at `/usr/local/bin/kubectl`, or download from here: https://kubernetes.io/docs/tasks/tools/install-kubectl/

**Comment by saladin101** [comment]
thank you for answer, my VM just have 2G memory,but i try to use

> ansible vm01 -m fetch -a "src=/usr/local/bin/kubectl dest={{ inventory_dir }}/artifacts"/

that is ok.
src and dest is same with kubespray/roles/kubernetes/client/tasks/main.yml

**Comment by dholt** [comment]
Which version of Ansible are you using? How much memory is on `localhost` and `vm01`? I would still try increasing RAM based on the memory error.

**Comment by cnf** [comment]
I am running into the same problem. Ansible is running from a vagrant virtualbox VM. The target is a DGX-1 with 512G ram.

**Comment by cnf** [comment]
@dholt as per the above, 

```
# ansible --version
ansible 2.7.11
```

ansible VM has 4G of ram, and as said, target is a DGX-1 with 512G ram.

ansible vm was created doing a vagrant up with a recent ubuntu image, and running `./scripts/setup.sh` in it.

**Comment by cnf** [comment]
I found https://github.com/kubernetes-sigs/kubespray/issues/5059, which looks like the same issue.

**Comment by supertetelman** [comment]
We've cheked in several changes to this code path and I believe it should either be fixed or no longer reproducible.
