### ISSUE TITLE
dgx-server role is missing nvsm dependencies

### ISSUE THREAD

**Issue by supertetelman** [NVIDIA/deepops#327]
After installing a fresh copy of CentOS 7 and running the dgx-server role, running nvsm show health results in:

```
ERROR:nvsm:Error communicating with NVSM API: Bad HTTP status code "500" from NVSM backend: Internal Server Error
WARNING:nvsm:Falling back to "nvsm-health --show"
Traceback (most recent call last):
 File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
   "__main__", mod_spec)
 File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
   exec(code, run_globals)
 File "/usr/share/nvsm-health/nvsmhealth/__main__.py", line 11, in <module>
   import nvsmhealth.monitor as monitor
 File "/usr/share/nvsm-health/nvsmhealth/monitor.py", line 19, in <module>
   from nvsmhealth.mqclient.endpoint import Endpoint
 File "/usr/share/nvsm-health/nvsmhealth/mqclient/endpoint.py", line 22, in <module>
   import urllib3
ModuleNotFoundError: No module named 'urllib3'

```
Installing additional packages with `python3.6 -m ensurepip && pip3 install urllib3` seems to resolve the issue.

**Comment by supertetelman** [comment]
This is probably related to an `nvsm` bug that was recently found and fixed. I'm closing this issue.
