### ISSUE TITLE
Failure: TASK [kubernetes/preinstall : Remove swapfile from /etc/fstab]

### ISSUE THREAD

**Issue by Abdelrahman44** [NVIDIA/deepops#360]
I am trying to experiment with deepops on a single workstation. I cloned the deepops repository, configured the inventory file, and trying to deploy kubernetes on the station but this task fails with a permission denied error as below:

`TASK [kubernetes/preinstall : Remove swapfile from /etc/fstab] *****************************************************************************
ok: [alienware2] => (item=swap)
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: IOError: [Errno 13] Permission denied: '/etc/fstab'
failed: [alienware2] (item=none) => changed=false 
  item: none
  module_stderr: |-
    Traceback (most recent call last):
      File "<stdin>", line 113, in <module>
      File "<stdin>", line 105, in _ansiballz_main
      File "<stdin>", line 48, in invoke_module
      File "/tmp/ansible_mount_payload_TaXrxg/__main__.py", line 714, in <module>
      File "/tmp/ansible_mount_payload_TaXrxg/__main__.py", line 654, in main
      File "/tmp/ansible_mount_payload_TaXrxg/__main__.py", line 323, in unset_mount
      File "/tmp/ansible_mount_payload_TaXrxg/__main__.py", line 139, in write_fstab
    IOError: [Errno 13] Permission denied: '/etc/fstab'
  module_stdout: ''
  msg: |-
    MODULE FAILURE
    See stdout/stderr for the exact error
  rc: 1
`

I think the problem can be solved by adding "become: true" to the cluster.yml file before playing kubernetes/preinstall role

**Comment by Abdelrahman44** [comment]
Just use -K and enter the password when playing the playbook, my bad
